#ifndef COMMON_WIDGETS_GLOBAL_H
#define COMMON_WIDGETS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMMON_WIDGETS_LIBRARY)
#  define COMMON_WIDGETS_EXPORT Q_DECL_EXPORT
#else
#  define COMMON_WIDGETS_EXPORT Q_DECL_IMPORT
#endif

#endif // COMMON_WIDGETS_GLOBAL_H
